# https://alacritty.org/config-alacritty.html

###########
# GENERAL #
###########

[general]

# Import additional configuration files
import = [ "~/.config/alacritty/tokyo-night.toml" ]

##########
# WINDOW #
##########

[window]

# Opacity
opacity = 0.8

########
# FONT #
########

[font]

# Normal font style
normal = { family = "JetbrainsMono Nerd Font", style = "Regular" }

############
# KEYBOARD #
############

[keyboard]

# Define keyboard bindings here
bindings = [
  #  { key = "n", mods = "Control", action = "SpawnNewInstance" },
  { key = "n", mods = "Control|Shift", action = "SpawnNewInstance" }
]
