autofit=70%
icc-profile=/home/angelogambara/Documents/GitHub Repos/dotfiles/local/share/color/icc/SW240 2_D65_L120_G22_2024-06-02T09.00.48Z.icm
stop-screensaver=no
volume=85
ytdl-format=best/bestvideo*+bestaudio
