stop-screensaver=no

[default]
profile=best
profile=panel
profile=short
profile=sway

[best]
ytdl-format=best/bestvideo*+bestaudio

[ytdl]
ytdl-format=bestvideo*+bestaudio/best

[gloss]
icc-profile=/home/angelogambara/Documents/GitHub Repos/dotfiles/local/share/color/icc/benq-sw240_i5-12400_gloss.icc

[matte]
icc-profile=/home/angelogambara/Documents/GitHub Repos/dotfiles/local/share/color/icc/benq-sw240_i5-12400_matte.icc

[panel]
icc-profile=/home/angelogambara/Documents/GitHub Repos/dotfiles/local/share/color/icc/benq-sw240_i5-12400_panel.icc

[short]
autofit=70%

[video]
autofit=80%

[movie]
autofit=90%

[sway]
volume=085

[xorg]
volume=100
