#!/bin/sh

export STATUSBAR=dwmblocks
export TERMINAL=alacritty
export XDG_SESSION_TYPE=x11

# shellcheck disable=1090
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

autostart="dunst dwmblocks notify-checkupdates picom rmddd unclutter"

mkdir -p /tmp/programs
set -f
for program in $autostart; do
  pgrep -u "$(id -un)" -x "$program" >/dev/null 2>&1 ||
    "$program" >"/tmp/programs/$program.log" 2>&1 &
done
set +f

setbg ~/.cache/wallpaper

xrandr --output DP-2 --auto
xrandr --output DisplayPort-1-2 --off

xset r rate 200 40
xset dpms 0 0 180

xrdb -load ~/.config/X11/gruvbox-dark.xresources

exec dwm
