#!/bin/sh
export XDG_SESSION_TYPE=x11

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    # shellcheck disable=1090
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xrandr --output DP-2 --auto --output DisplayPort-1-2 --off --right-of DP-2
xset r rate 330 50 dpms 0 0 300
xrdb -load ~/.config/X11/themes/macchiato.Xresources

feh --no-fehbg --bg-fill '/home/angelo/.cache/setbg'

autostart="\
    dunst
    dwmblocks
    fcitx5
    notify-checkupdates
    udiskie"

echo "$autostart" | while read -r program; do
  process="${program%%[[:space:]]*}"
  process="${process##*/}"
  pidof -s "$process" || $program >"/tmp/$process.log" 2>&1 &
done
picom &

exec dwm >/tmp/dwm.log 2>&1
