#!/bin/sh

# =========================
# Configure
# =========================

# Set X11_CONFIG_HOME
if [ -z "$X11_CONFIG_HOME" ]; then
  # Get directory from XINITRC
  if [ -n "$XINITRC" ]; then
    X11_CONFIG_HOME=$(dirname "$XINITRC")
  else
    X11_CONFIG_HOME=$HOME
  fi
fi

# =========================
# Run-parts
# =========================

# Source each file in order
if [ -d "$X11_CONFIG_HOME"/xinitrc.d ]; then
  for f in "$X11_CONFIG_HOME"/xinitrc.d/?*.sh; do
    # shellcheck disable=1090
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# =========================
# Window Manager
# =========================

# Replace shell with window manager
exec dwm >/tmp/dwm.log 2>&1
