listener {
    timeout = 180
    on-timeout = swaymsg output * dpms off
    on-resume = swaymsg output * dpms on
}

listener {
    timeout = 180
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 300
    on-timeout = sudo zzz
}
