listener {
    timeout = 150
    on-timeout = hyprctl dispatch dpms off
    on-resume  = hyprctl dispatch dpms on
}

listener {
    timeout = 300
    on-timeout = pgrep hyprlock || hyprlock & systemctl suspend
}

listener {
    timeout = 30
    on-timeout = pgrep hyprlock && systemctl suspend
}
