disableStartupPopups: true
gui:
  sidePanels:
    - [files]
    - [status]
    - [branches]
    - [commits]
    - [stash]
  showBottomLine: false
  showCommandLog: false
  showRandomTip: false
  showRootItemInFileTree: false
git:
  diffRenderers:
    - colorArg: always
      command: delta --paging=never
keybinding:
  universal:
    focusMainView: "0"
    jumpToBlock:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
customCommands:
  - key: "C"
    command: 'git commit -m "{{ .Form.Type }}{{if .Form.Scopes}}({{ .Form.Scopes }}){{end}}{{ .Form.Breaking }}: {{ .Form.Description }}"'
    description: "Commit changes using conventional commits"
    context: "files"
    prompts:
      - type: "menu"
        title: "Select Commit Type"
        key: "Type"
        options:
          - name: "Feature"
            description: "Introduces a noticible feature (may trigger MINOR version)"
            value: "feat"
          - name: "Fix"
            description: "Fixes a bug in production (may trigger PATCH version)"
            value: "fix"
          - name: "Refactor"
            description: "Improves code (elegance, simplicy, readability, maintain.)"
            value: "refactor"
          - name: "Style"
            description: ""
            value: "style"
          - name: "Performance"
            description: ""
            value: "perf"
          - name: "Documentation"
            description: ""
            value: "docs"
          - name: "Test"
            description: ""
            value: "test"
          - name: "CI"
            description: "E.g., Dockerfiles, GitHub workflows, git hooks and scripts"
            value: "ci"
          - name: "Build"
            description: "E.g., updating a library or dependency, creating a tag"
            value: "build"
          - name: "Maintenance"
            description: "Nothing productive: symlinking files, renaming, moving"
            value: "chore"
          - name: "WIP"
            description: "Do not use in production (don't forget to push!)"
            value: "wip"

      - type: "menu"
        title: "Is this a breaking change?"
        key: "Breaking"
        options:
          - name: "No"
            description: "Standard non-breaking change"
            value: ""
          - name: "Yes"
            description: "Breaks backward compatibility (triggers MAJOR version)"
            value: "!"

      - type: "input"
        title: "Optional scope (e.g., auth, billing, search, ui)"
        key: "Scopes"

      - type: "input"
        title: "Commit description"
        key: "Description"

      - type: "confirm"
        title: "Commit your changes?"
        body: "{{ .Form.Type }}{{if .Form.Scopes}}({{ .Form.Scopes }}){{end}}{{ .Form.Breaking }}: {{ .Form.Description }}"
