[general]
import = [
  "~/.config/alacritty/gruvbox-dark.toml"
]

[window]
opacity = 0.8

[font]
size = 15.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", command = { program = "sh", args = ["-c", "WORKDIR_SET=1 alacritty"] } },

  { key = "U", mods = "Control|Shift", action = "ScrollHalfPageUp"   },
  { key = "D", mods = "Control|Shift", action = "ScrollHalfPageDown" },

  { key = "J", mods = "Control|Shift", action = "ScrollLineUp"   },
  { key = "K", mods = "Control|Shift", action = "ScrollLineDown" },
]
