set document.history.global.enable = 0
set document.uri_passing.play.command = "mpv --shuffle %c > /dev/null 2>&1"
set document.uri_passing.view.command = "sxiv -pa %c > /dev/null 2>&1"

bind "main" "h" = "history-move-back"
bind "main" "j" = "move-link-next"
bind "main" "k" = "move-link-prev"
bind "main" "l" = "link-follow"
bind "main" "e" = "link-external-command"
bind "main" "Ctrl-D" = "move-half-page-down"
bind "main" "Ctrl-U" = "move-half-page-up"

set cookies.max_age = 0

bind "menu" "h" = "left"
bind "menu" "j" = "down"
bind "menu" "k" = "up"
bind "menu" "l" = "right"
